/* Formatted on 20/06/2016 14:59:12 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF



COLUMN PROID0NIVEL FORMAT A15 TRUNC NEW_VALUE V_PROID0NIVEL
COLUMN PROID1NIVEL FORMAT A15 TRUNC NEW_VALUE V_PROID1NIVEL
COLUMN PROID2NIVEL FORMAT A15 TRUNC NEW_VALUE V_PROID2NIVEL
COLUMN PES_ID_0 FORMAT A15 TRUNC NEW_VALUE V_PES_ID_0
COLUMN PES_ID_1 FORMAT A15 TRUNC NEW_VALUE V_PES_ID_1
COLUMN PES_ID_2 FORMAT A15 TRUNC NEW_VALUE V_PES_ID_2
COLUMN PTR_ID FORMAT A15 TRUNC NEW_VALUE V_PTR_ID
COLUMN PAC_ID FORMAT A15 TRUNC NEW_VALUE V_PAC_ID
COLUMN CIE_ID FORMAT A15 TRUNC NEW_VALUE V_CIE_ID
COLUMN HOR_ID FORMAT A15 TRUNC NEW_VALUE V_HOR_ID
COLUMN PTR_SESIONES FORMAT A15 TRUNC NEW_VALUE V_PTR_SESIONES
COLUMN PTR_FECHA_CREACION FORMAT A15 TRUNC NEW_VALUE V_PTR_FECHA_CREACION
COLUMN PTR_FECHA_INICIO FORMAT A15 TRUNC NEW_VALUE V_PTR_FECHA_INICIO
COLUMN PTR_FECHA_FIN FORMAT A15 TRUNC NEW_VALUE V_PTR_FECHA_FIN
COLUMN PTR_ESTADO FORMAT A15 TRUNC NEW_VALUE V_PTR_ESTADO
COLUMN PTR_NUM_SESIONES FORMAT A15 TRUNC NEW_VALUE V_PTR_NUM_SESIONES
COLUMN PTR_DIAS FORMAT A15 TRUNC NEW_VALUE V_PTR_DIAS
COLUMN PTR_CODIGO_TARIFARIO FORMAT A15 TRUNC NEW_VALUE V_PTR_CODIGO_TARIFARIO
COLUMN TER_ID FORMAT A15 TRUNC NEW_VALUE V_TER_ID
COLUMN CIN_NUMERO FORMAT A15 TRUNC NEW_VALUE V_CIN_NUMERO
COLUMN PTR_HJA_EVOL FORMAT A15 TRUNC NEW_VALUE V_PTR_HJA_EVOL
COLUMN PME_ID_PLANIF FORMAT A15 TRUNC NEW_VALUE V_PME_ID_PLANIF
COLUMN PTR_TIPO_PLANIF FORMAT A15 TRUNC NEW_VALUE V_PTR_TIPO_PLANIF
COLUMN PTR_DIAGNOSTICO_MEDICO FORMAT A15 TRUNC NEW_VALUE V_PTR_DIAGNOSTICO_MEDICO
COLUMN PTR_OBSERVACION FORMAT A15 TRUNC NEW_VALUE V_PTR_OBSERVACION
COLUMN UNS_ID FORMAT A15 TRUNC NEW_VALUE V_UNS_ID
COLUMN CTR_ID FORMAT A15 TRUNC NEW_VALUE V_CTR_ID
COLUMN CTR_ORDEN_SESION FORMAT A15 TRUNC NEW_VALUE V_CTR_ORDEN_SESION
COLUMN CTR_FECHA FORMAT A15 TRUNC NEW_VALUE V_CTR_FECHA
COLUMN CTR_ESTADO FORMAT A15 TRUNC NEW_VALUE V_CTR_ESTADO
COLUMN CTR_OBSERVACION FORMAT A15 TRUNC NEW_VALUE V_CTR_OBSERVACION
COLUMN PME_ID_CAB FORMAT A15 TRUNC NEW_VALUE V_PME_ID_CAB
COLUMN DTR_ID FORMAT A15 TRUNC NEW_VALUE V_DTR_ID
COLUMN TTE_ID FORMAT A15 TRUNC NEW_VALUE V_TTE_ID
COLUMN DTR_HORA_INICIO FORMAT A15 TRUNC NEW_VALUE V_DTR_HORA_INICIO
COLUMN DTR_HORA_FIN FORMAT A15 TRUNC NEW_VALUE V_DTR_HORA_FIN
COLUMN DTR_OBSERVACION FORMAT A15 TRUNC NEW_VALUE V_DTR_OBSERVACION
COLUMN DTR_FECHA_CREACION FORMAT A15 TRUNC NEW_VALUE V_DTR_FECHA_CREACION
COLUMN DTR_ESTADO FORMAT A15 TRUNC NEW_VALUE V_DTR_ESTADO
COLUMN DTR_PROCEDIMIENTO_DESCRIP FORMAT A15 TRUNC NEW_VALUE V_DTR_PROCEDIMIENTO_DESCRIP
COLUMN DTR_CHEQUEO FORMAT A15 TRUNC NEW_VALUE V_DTR_CHEQUEO
COLUMN PME_ID_DETALL FORMAT A15 TRUNC NEW_VALUE V_PME_ID_DETALL


  SELECT DISTINCT V_MIGRA_TODO.PROID0NIVEL,
                  V_MIGRA_TODO.PTR_ID,
                  V_MIGRA_TODO.PAC_ID,
                  V_MIGRA_TODO.CIE_ID,
                  V_MIGRA_TODO.HOR_ID,
                  V_MIGRA_TODO.PTR_SESIONES,
                  V_MIGRA_TODO.PTR_FECHA_CREACION,
                  V_MIGRA_TODO.PTR_FECHA_INICIO,
                  V_MIGRA_TODO.PTR_FECHA_FIN,
                  V_MIGRA_TODO.PTR_ESTADO,
                  V_MIGRA_TODO.PTR_NUM_SESIONES,
                  V_MIGRA_TODO.PTR_DIAS,
                  V_MIGRA_TODO.PTR_CODIGO_TARIFARIO,
                  V_MIGRA_TODO.TER_ID,
                  V_MIGRA_TODO.CIN_NUMERO,
                  V_MIGRA_TODO.PTR_HJA_EVOL,
                  V_MIGRA_TODO.PME_ID_PLANIF,
                  V_MIGRA_TODO.PTR_TIPO_PLANIF,
                  V_MIGRA_TODO.PTR_DIAGNOSTICO_MEDICO,
                  V_MIGRA_TODO.PTR_OBSERVACION,
                  V_MIGRA_TODO.UNS_ID
    FROM ADMINISTRATIVO.V_MIGRA_TODO
   WHERE V_MIGRA_TODO.PTR_ID IN '&&1'
ORDER BY V_MIGRA_TODO.PROID0NIVEL;



DECLARE
   TYPE T_V_MIGRA_TODO IS TABLE OF ADMINISTRATIVO.V_MIGRA_TODO%ROWTYPE;

   V_T_V_MIGRA_TODO   T_V_MIGRA_TODO := T_V_MIGRA_TODO ();

   CURSOR c1
   IS
        SELECT DISTINCT V_MIGRA_TODO.PROID0NIVEL,
                        V_MIGRA_TODO.PTR_ID,
                        V_MIGRA_TODO.PAC_ID,
                        V_MIGRA_TODO.CIE_ID,
                        V_MIGRA_TODO.HOR_ID,
                        V_MIGRA_TODO.PTR_SESIONES,
                        V_MIGRA_TODO.PTR_FECHA_CREACION,
                        V_MIGRA_TODO.PTR_FECHA_INICIO,
                        V_MIGRA_TODO.PTR_FECHA_FIN,
                        V_MIGRA_TODO.PTR_ESTADO,
                        V_MIGRA_TODO.PTR_NUM_SESIONES,
                        V_MIGRA_TODO.PTR_DIAS,
                        V_MIGRA_TODO.PTR_CODIGO_TARIFARIO,
                        V_MIGRA_TODO.TER_ID,
                        V_MIGRA_TODO.CIN_NUMERO,
                        V_MIGRA_TODO.PTR_HJA_EVOL,
                        V_MIGRA_TODO.PME_ID_PLANIF,
                        V_MIGRA_TODO.PTR_TIPO_PLANIF,
                        V_MIGRA_TODO.PTR_DIAGNOSTICO_MEDICO,
                        V_MIGRA_TODO.PTR_OBSERVACION,
                        V_MIGRA_TODO.UNS_ID
          FROM ADMINISTRATIVO.V_MIGRA_TODO
         WHERE V_MIGRA_TODO.PTR_ID IN '&&1'
      ORDER BY V_MIGRA_TODO.PROID0NIVEL;

   V_PROID0NIVEL      PLS_INTEGER;

   CURSOR c2
   IS
        SELECT DISTINCT V_MIGRA_TODO.CTR_ID,
                        V_MIGRA_TODO.CTR_ORDEN_SESION,
                        V_MIGRA_TODO.CTR_FECHA,
                        V_MIGRA_TODO.CTR_ESTADO,
                        V_MIGRA_TODO.CTR_OBSERVACION,
                        V_MIGRA_TODO.PME_ID_CAB
          FROM ADMINISTRATIVO.V_MIGRA_TODO
         WHERE V_MIGRA_TODO.PTR_ID = '&&1'
      ORDER BY V_MIGRA_TODO.CTR_ORDEN_SESION;

   V_CTR_ID           PLS_INTEGER;
BEGIN
   FOR X IN C1
   LOOP
      INSERT
        INTO ADMINISTRATIVO.MED_SOLICITUD_PROCEDIMIENTO (
                MED_SOLICITUD_PROCEDIMIENTO.SPR_ID,
                MED_SOLICITUD_PROCEDIMIENTO.PAC_ID,
                MED_SOLICITUD_PROCEDIMIENTO.CIE_ID,
                MED_SOLICITUD_PROCEDIMIENTO.PME_ID,
                MED_SOLICITUD_PROCEDIMIENTO.PES_ID,
                MED_SOLICITUD_PROCEDIMIENTO.CIN_NUMERO,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_NUM_SOLICITUD,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_SESIONES,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_INICIO,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_FIN,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_SESIONES_REALIZADAS,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_DIAS,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_CODIGO_TARIFARIO,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_HJA_EVOL,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_DIAGNOSTICO_MEDICO,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_OBSERVACION,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_ESTADO,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_CREACION,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_COLOR,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_INTENSIDAD,
                MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_AGENDADO)
      VALUES (                         /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_ID*/
              -1,
              /*:MED_SOLICITUD_PROCEDIMIENTO.PAC_ID*/
              X.PAC_ID,
              /*:MED_SOLICITUD_PROCEDIMIENTO.CIE_ID*/
              X.CIE_ID,
              /*:MED_SOLICITUD_PROCEDIMIENTO.PME_ID*/
              X.PME_ID_PLANIF,
              /*:MED_SOLICITUD_PROCEDIMIENTO.PES_ID*/
              X.PROID0NIVEL,
              /*:MED_SOLICITUD_PROCEDIMIENTO.CIN_NUMERO*/
              X.CIN_NUMERO,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_NUM_SOLICITUD*/
              NULL,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_SESIONES*/
              X.PTR_SESIONES,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_INICIO*/
              X.PTR_FECHA_INICIO,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_FIN*/
              X.PTR_FECHA_FIN,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_SESIONES_REALIZADAS*/
              NULL,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_DIAS*/
              X.PTR_DIAS,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_CODIGO_TARIFARIO*/
              X.PTR_CODIGO_TARIFARIO,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPRL*/
              X.PTR_HJA_EVOL,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_DIAGNOSTICO_MEDICO*/
              X.PTR_DIAGNOSTICO_MEDICO,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_OBSERVACION*/
              X.PTR_OBSERVACION,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_ESTADO*/
              X.PTR_ESTADO,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_CREACION*/
              X.PTR_FECHA_CREACION,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_COLOR*/
              NULL,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_INTENSIDAD*/
              NULL,
              /*:MED_SOLICITUD_PROCEDIMIENTO.SPR_FECHA_AGENDADO*/
              X.PTR_FECHA_INICIO);

      V_PROID0NIVEL := X.PROID0NIVEL;


      FOR Y IN C2
      LOOP
         INSERT
           INTO ADMINISTRATIVO.MED_TURNO_PROCEDIMIENTO (
                   MED_TURNO_PROCEDIMIENTO.TPR_ID,
                   MED_TURNO_PROCEDIMIENTO.SPR_ID,
                   MED_TURNO_PROCEDIMIENTO.USU_ID,
                   MED_TURNO_PROCEDIMIENTO.PSC_ID,
                   MED_TURNO_PROCEDIMIENTO.TPR_NUM_SESION,
                   MED_TURNO_PROCEDIMIENTO.TPR_FECHA_CREACION,
                   MED_TURNO_PROCEDIMIENTO.TPR_FECHA_TURNO,
                   MED_TURNO_PROCEDIMIENTO.TPR_ESTADO,
                   MED_TURNO_PROCEDIMIENTO.TPR_FECHA_INACTIVACION,
                   MED_TURNO_PROCEDIMIENTO.TPR_REPLANIFICADO,
                   MED_TURNO_PROCEDIMIENTO.PRO_ID_N1)
         VALUES (                          /*:MED_TURNO_PROCEDIMIENTO.TPR_ID*/
                 -1,
                 /*:MED_TURNO_PROCEDIMIENTO.SPR_ID*/
                 SEQ_MED_SOLICITUD_PROC.CURRVAL,
                 /*:MED_TURNO_PROCEDIMIENTO.USU_ID*/
                 NULL,
                 /*:MED_TURNO_PROCEDIMIENTO.PSC_ID*/
                 NULL,
                 /*:MED_TURNO_PROCEDIMIENTO.TPR_NUM_SESION*/
                 Y.CTR_ORDEN_SESION,
                 /*:MED_TURNO_PROCEDIMIENTO.TPR_FECHA_CREACION*/
                 SYSDATE,
                 /*:MED_TURNO_PROCEDIMIENTO.TPR_FECHA_TURNO*/
                 Y.CTR_FECHA,
                 /*:MED_TURNO_PROCEDIMIENTO.TPR_ESTADO*/
                 Y.CTR_ESTADO,
                 /*:MED_TURNO_PROCEDIMIENTO.TPR_FECHA_INACTIVACION*/
                 NULL,
                 /*:MED_TURNO_PROCEDIMIENTO.TPR_REPLANIFICADO*/
                 NULL,
                 /*:MED_TURNO_PROCEDIMIENTO.PRO_ID_N1*/
                 NULL);

         V_CTR_ID := Y.CTR_ID;
         
         
         
      END LOOP;
   END LOOP;
END;


SELECT *
  FROM MED_SOLICITUD_PROCEDIMIENTO
 WHERE PAC_ID = '&&V_PAC_ID';


SELECT MED_TURNO_PROCEDIMIENTO.TPR_ID,
       MED_TURNO_PROCEDIMIENTO.SPR_ID,
       MED_TURNO_PROCEDIMIENTO.USU_ID,
       MED_TURNO_PROCEDIMIENTO.PSC_ID,
       MED_TURNO_PROCEDIMIENTO.TPR_NUM_SESION,
       MED_TURNO_PROCEDIMIENTO.TPR_FECHA_CREACION,
       MED_TURNO_PROCEDIMIENTO.TPR_FECHA_TURNO,
       MED_TURNO_PROCEDIMIENTO.TPR_ESTADO,
       MED_TURNO_PROCEDIMIENTO.TPR_FECHA_INACTIVACION,
       MED_TURNO_PROCEDIMIENTO.TPR_REPLANIFICADO,
       MED_TURNO_PROCEDIMIENTO.PRO_ID_N1
  FROM ADMINISTRATIVO.MED_SOLICITUD_PROCEDIMIENTO
       INNER JOIN ADMINISTRATIVO.MED_TURNO_PROCEDIMIENTO
          ON (MED_SOLICITUD_PROCEDIMIENTO.SPR_ID =
                 MED_TURNO_PROCEDIMIENTO.SPR_ID)
 WHERE MED_SOLICITUD_PROCEDIMIENTO.PAC_ID = '&&V_PAC_ID';

ROLLBACK