/* Formatted on 13/06/2016 13:26:58 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
COLUMN TTE_ID FORMAT A20 TRUNC NEW_VALUE V_TTE_ID
COLUMN TER_ID FORMAT A20 TRUNC NEW_VALUE V_TER_ID
COLUMN TER_DESCRIPCION FORMAT A20 TRUNC NEW_VALUE V_TER_DESCRIPCION
COLUMN TRA_DESCRIPCION FORMAT A40 TRUNC NEW_VALUE V_TRA_DESCRIPCION
COLUMN REVISADO FORMAT A20 TRUNC NEW_VALUE V_REVISADO
COLUMN PROID3NIVEL FORMAT A20 TRUNC NEW_VALUE V_PROID3NIVEL


REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2
REM ACA EN LA TABLA DE PROCEDIMIENTO Y EQUIVALENCIA Y DEJA GRABADO EL NIVEL 2


SELECT AA_TABLA_EQUIV_PROCED.TTE_ID,
       AA_TABLA_EQUIV_PROCED.TER_ID,
       AA_TABLA_EQUIV_PROCED.TER_DESCRIPCION,
       AA_TABLA_EQUIV_PROCED.TRA_DESCRIPCION,
       AA_TABLA_EQUIV_PROCED.REVISADO,
       AA_TABLA_EQUIV_PROCED.PROID2NIVEL
  FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
 WHERE ROWNUM = 1 AND REVISADO = 0;


PAUSE INGRESE
COLUMN PRO_DESCRIPCION HEADING "PRO_DESCRIPCION" FORMAT A10  TRUNC  NEW_VALUE V_PRO_DESCRIPCION
COLUMN DESCRIPCION3 HEADING "DESCRIPCION3" FORMAT A30  TRUNC  NEW_VALUE V_DESCRIPCION3
COLUMN D1 HEADING "D1" FORMAT A30  TRUNC  NEW_VALUE V_D1
COLUMN D2 HEADING "D2" FORMAT A30  TRUNC  NEW_VALUE V_D2
COLUMN PRO_ID HEADING "PRO_ID" FORMAT A10  TRUNC  NEW_VALUE V_PRO_ID


  SELECT P0.PRO_DESCRIPCION D1,
         P1.PRO_DESCRIPCION D2,
         P2.PRO_ID,
         P2.PRO_DESCRIPCION DESCRIPCION3
    FROM ADMINISTRATIVO.V_PROCED_TRES_NIV,
         ADMINISTRATIVO.MED_PROCEDIMIENTO P0,
         ADMINISTRATIVO.MED_PROCEDIMIENTO P1,
         ADMINISTRATIVO.MED_PROCEDIMIENTO P2
   WHERE     P2.PRO_ID = V_PROCED_TRES_NIV.NIVEL2_PRO_ID
         AND P1.PRO_ID = V_PROCED_TRES_NIV.NIVEL1_PRO_ID
         AND P0.PRO_ID = V_PROCED_TRES_NIV.NIVEL0_PRO_ID
         AND UTL_MATCH.EDIT_DISTANCE_SIMILARITY (P2.PRO_DESCRIPCION,
                                                 '&&V_TRA_DESCRIPCION.') > 95
ORDER BY P0.PRO_DESCRIPCION, P1.PRO_DESCRIPCION, P2.PRO_DESCRIPCION;

PAUSE &&V_PRO_ID.




UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.REVISADO = 1,
       AA_TABLA_EQUIV_PROCED.PROID2NIVEL = '&&V_PRO_ID.'
 WHERE     AA_TABLA_EQUIV_PROCED.TTE_ID = '&&V_TTE_ID.'
       AND TER_ID = '&&V_TER_ID.';


BEGIN
   IF TRIM (UPPER ('&&GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/