/* Formatted on 20/06/2016 13:40:40 (QP5 v5.252.13127.32867) */
CREATE OR REPLACE FORCE VIEW ADMINISTRATIVO.V_MIGRA_DETALL_TRA
(
   PTR_ID,
   PAC_ID,
   CIE_ID,
   HOR_ID,
   PTR_SESIONES,
   PTR_FECHA_CREACION,
   PTR_FECHA_INICIO,
   PTR_FECHA_FIN,
   PTR_ESTADO,
   PTR_NUM_SESIONES,
   PTR_DIAS,
   PTR_CODIGO_TARIFARIO,
   TER_ID,
   CIN_NUMERO,
   PTR_HJA_EVOL,
   PME_ID_PLANIF,
   PTR_TIPO_PLANIF,
   PTR_DIAGNOSTICO_MEDICO,
   PTR_OBSERVACION,
   UNS_ID,
   CTR_ID,
   CTR_ORDEN_SESION,
   CTR_FECHA,
   CTR_ESTADO,
   CTR_OBSERVACION,
   PME_ID_CAB,
   DTR_ID,
   TTE_ID,
   DTR_HORA_INICIO,
   DTR_HORA_FIN,
   DTR_OBSERVACION,
   DTR_FECHA_CREACION,
   DTR_ESTADO,
   DTR_PROCEDIMIENTO_DESCRIP,
   DTR_CHEQUEO,
   PME_ID_DETALL
)
AS
   SELECT V_MIGRA_CAB_TRAT.PTR_ID,
          V_MIGRA_CAB_TRAT.PAC_ID,
          V_MIGRA_CAB_TRAT.CIE_ID,
          V_MIGRA_CAB_TRAT.HOR_ID,
          V_MIGRA_CAB_TRAT.PTR_SESIONES,
          V_MIGRA_CAB_TRAT.PTR_FECHA_CREACION,
          V_MIGRA_CAB_TRAT.PTR_FECHA_INICIO,
          V_MIGRA_CAB_TRAT.PTR_FECHA_FIN,
          V_MIGRA_CAB_TRAT.PTR_ESTADO,
          V_MIGRA_CAB_TRAT.PTR_NUM_SESIONES,
          V_MIGRA_CAB_TRAT.PTR_DIAS,
          V_MIGRA_CAB_TRAT.PTR_CODIGO_TARIFARIO,
          V_MIGRA_CAB_TRAT.TER_ID,
          V_MIGRA_CAB_TRAT.CIN_NUMERO,
          V_MIGRA_CAB_TRAT.PTR_HJA_EVOL,
          V_MIGRA_CAB_TRAT.PME_ID_PLANIF,
          V_MIGRA_CAB_TRAT.PTR_TIPO_PLANIF,
          V_MIGRA_CAB_TRAT.PTR_DIAGNOSTICO_MEDICO,
          V_MIGRA_CAB_TRAT.PTR_OBSERVACION,
          V_MIGRA_CAB_TRAT.UNS_ID,
          V_MIGRA_CAB_TRAT.CTR_ID,
          V_MIGRA_CAB_TRAT.CTR_ORDEN_SESION,
          V_MIGRA_CAB_TRAT.CTR_FECHA,
          V_MIGRA_CAB_TRAT.CTR_ESTADO,
          V_MIGRA_CAB_TRAT.CTR_OBSERVACION,
          V_MIGRA_CAB_TRAT.PME_ID_CAB,
          MEF_DET_TRATAM.DTR_ID,
          MEF_DET_TRATAM.TTE_ID,
          MEF_DET_TRATAM.DTR_HORA_INICIO,
          MEF_DET_TRATAM.DTR_HORA_FIN,
          MEF_DET_TRATAM.DTR_OBSERVACION,
          MEF_DET_TRATAM.DTR_FECHA_CREACION,
          MEF_DET_TRATAM.DTR_ESTADO,
          MEF_DET_TRATAM.DTR_PROCEDIMIENTO_DESCRIP,
          MEF_DET_TRATAM.DTR_CHEQUEO,
          MEF_DET_TRATAM.PME_ID PME_ID_DETALL
     FROM ADMINISTRATIVO.V_MIGRA_CAB_TRAT
          FULL OUTER JOIN ADMINISTRATIVO.MEF_DET_TRATAM
             ON (V_MIGRA_CAB_TRAT.CTR_ID = MEF_DET_TRATAM.CTR_ID);



CREATE OR REPLACE VIEW v_migra_todo
AS
     SELECT (SELECT AA_TABLA_EQUIV_PROCED.PROID0NIVEL
               FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
              WHERE AA_TABLA_EQUIV_PROCED.TTE_ID = V_MIGRA_DETALL_TRA.TTE_ID)
               PROID0NIVEL,
            (SELECT AA_TABLA_EQUIV_PROCED.PROID1NIVEL
               FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
              WHERE AA_TABLA_EQUIV_PROCED.TTE_ID = V_MIGRA_DETALL_TRA.TTE_ID)
               PROID1NIVEL,
            (SELECT AA_TABLA_EQUIV_PROCED.PROID2NIVEL
               FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
              WHERE AA_TABLA_EQUIV_PROCED.TTE_ID = V_MIGRA_DETALL_TRA.TTE_ID)
               PROID2NIVEL,
            (SELECT AA_TABLA_EQUIV_PROCED.PES_ID_0
               FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
              WHERE AA_TABLA_EQUIV_PROCED.TTE_ID = V_MIGRA_DETALL_TRA.TTE_ID)
               PES_ID_0,
            (SELECT AA_TABLA_EQUIV_PROCED.PES_ID_1
               FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
              WHERE AA_TABLA_EQUIV_PROCED.TTE_ID = V_MIGRA_DETALL_TRA.TTE_ID)
               PES_ID_1,
            (SELECT AA_TABLA_EQUIV_PROCED.PES_ID_2
               FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
              WHERE AA_TABLA_EQUIV_PROCED.TTE_ID = V_MIGRA_DETALL_TRA.TTE_ID)
               PES_ID_2,
            V_MIGRA_DETALL_TRA.PTR_ID,
            V_MIGRA_DETALL_TRA.PAC_ID,
            V_MIGRA_DETALL_TRA.CIE_ID,
            V_MIGRA_DETALL_TRA.HOR_ID,
            V_MIGRA_DETALL_TRA.PTR_SESIONES,
            V_MIGRA_DETALL_TRA.PTR_FECHA_CREACION,
            V_MIGRA_DETALL_TRA.PTR_FECHA_INICIO,
            V_MIGRA_DETALL_TRA.PTR_FECHA_FIN,
            V_MIGRA_DETALL_TRA.PTR_ESTADO,
            V_MIGRA_DETALL_TRA.PTR_NUM_SESIONES,
            V_MIGRA_DETALL_TRA.PTR_DIAS,
            V_MIGRA_DETALL_TRA.PTR_CODIGO_TARIFARIO,
            V_MIGRA_DETALL_TRA.TER_ID,
            V_MIGRA_DETALL_TRA.CIN_NUMERO,
            V_MIGRA_DETALL_TRA.PTR_HJA_EVOL,
            V_MIGRA_DETALL_TRA.PME_ID_PLANIF,
            V_MIGRA_DETALL_TRA.PTR_TIPO_PLANIF,
            V_MIGRA_DETALL_TRA.PTR_DIAGNOSTICO_MEDICO,
            V_MIGRA_DETALL_TRA.PTR_OBSERVACION,
            V_MIGRA_DETALL_TRA.UNS_ID,
            V_MIGRA_DETALL_TRA.CTR_ID,
            V_MIGRA_DETALL_TRA.CTR_ORDEN_SESION,
            V_MIGRA_DETALL_TRA.CTR_FECHA,
            V_MIGRA_DETALL_TRA.CTR_ESTADO,
            V_MIGRA_DETALL_TRA.CTR_OBSERVACION,
            V_MIGRA_DETALL_TRA.PME_ID_CAB,
            V_MIGRA_DETALL_TRA.DTR_ID,
            V_MIGRA_DETALL_TRA.TTE_ID,
            V_MIGRA_DETALL_TRA.DTR_HORA_INICIO,
            V_MIGRA_DETALL_TRA.DTR_HORA_FIN,
            V_MIGRA_DETALL_TRA.DTR_OBSERVACION,
            V_MIGRA_DETALL_TRA.DTR_FECHA_CREACION,
            V_MIGRA_DETALL_TRA.DTR_ESTADO,
            V_MIGRA_DETALL_TRA.DTR_PROCEDIMIENTO_DESCRIP,
            V_MIGRA_DETALL_TRA.DTR_CHEQUEO,
            V_MIGRA_DETALL_TRA.PME_ID_DETALL
       FROM ADMINISTRATIVO.V_MIGRA_DETALL_TRA       
   ORDER BY V_MIGRA_DETALL_TRA.TTE_ID, V_MIGRA_DETALL_TRA.CTR_ORDEN_SESION