REM DROP TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED CASCADE CONSTRAINTS;
REM 
REM CREATE TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM (
REM   TTE_ID           INTEGER,
REM   TER_ID           INTEGER,
REM   TER_DESCRIPCION  VARCHAR2(500 BYTE),
REM   TRA_DESCRIPCION  VARCHAR2(500 BYTE),
REM   REVISADO         INTEGER                      DEFAULT 0,
REM   PROID0NIVEL      INTEGER                      DEFAULT 0,
REM   PROID1NIVEL      INTEGER                      DEFAULT 0,
REM   PROID2NIVEL      INTEGER                      DEFAULT 0
REM );
REM 
REM 
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (21, 5, 'ELECTROTERAPIA', 'ACUPRESOR RELAJANTE', 1, 
REM     1, 6, 30);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (20, 5, 'ELECTROTERAPIA', 'COMPEX', 1, 
REM     1, 6, 29);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (9, 5, 'ELECTROTERAPIA', 'CORRIENTES GALVANICAS', 1, 
REM     1, 6, 18);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (10, 5, 'ELECTROTERAPIA', 'CORRIENTES INTERFERENCIALES', 1, 
REM     1, 6, 19);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (11, 5, 'ELECTROTERAPIA', 'CORRIENTES METABOLICAS', 1, 
REM     1, 6, 20);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (18, 5, 'ELECTROTERAPIA', 'DIATERMIA', 1, 
REM     1, 6, 27);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (12, 5, 'ELECTROTERAPIA', 'ELECTRO ESTIMULACION', 1, 
REM     1, 6, 21);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (13, 5, 'ELECTROTERAPIA', 'IONIZACIONES', 1, 
REM     1, 6, 22);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (14, 5, 'ELECTROTERAPIA', 'LASERTERAPIA', 1, 
REM     1, 6, 23);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (17, 5, 'ELECTROTERAPIA', 'MAGNETOTERAPIA', 1, 
REM     1, 6, 26);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (22, 5, 'ELECTROTERAPIA', 'MASAJE', 1, 
REM     1, 6, 31);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (24, 5, 'ELECTROTERAPIA', 'ONDAS DE CHOQUE', 1, 
REM     1, 6, 4);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (19, 5, 'ELECTROTERAPIA', 'RAYOS ULTRAVIOLETA', 1, 
REM     1, 6, 28);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (16, 5, 'ELECTROTERAPIA', 'SONOFORESIS', 1, 
REM     1, 6, 25);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (23, 5, 'ELECTROTERAPIA', 'TRACCION MANUAL CERVICAL / MOVILIDAD', 1, 
REM     1, 6, 32);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (15, 5, 'ELECTROTERAPIA', 'ULTRASONIDO', 1, 
REM     1, 6, 24);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (7, 4, 'HIDROTERAPIA', 'COMPRESA QUIMICA CALIENTE', 1, 
REM     1, 5, 16);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (8, 4, 'HIDROTERAPIA', 'COMPRESA QUIMICA FRIA', 1, 
REM     1, 5, 17);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (1, 4, 'HIDROTERAPIA', 'PARAFINA', 1, 
REM     1, 5, 10);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (6, 4, 'HIDROTERAPIA', 'PISCINA', 1, 
REM     1, 5, 15);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (2, 4, 'HIDROTERAPIA', 'TANQUE DE HUBARD', 1, 
REM     1, 5, 11);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (4, 4, 'HIDROTERAPIA', 'TANQUE DE REMOLINO DE MIEMBROS INFERIORES', 1, 
REM     1, 5, 13);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (3, 4, 'HIDROTERAPIA', 'TANQUE DE REMOLINO DE MIEMBROS SUPERIORES', 1, 
REM     1, 5, 12);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (5, 4, 'HIDROTERAPIA', 'TANQUE TERAPEUTICO LUMBAR', 1, 
REM     1, 5, 14);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (42, 6, 'MECANOTERAPIA GIMNASIO', 'BICICLETA ESTACIONARIA', 1, 
REM     1, 6, 48);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (44, 6, 'MECANOTERAPIA GIMNASIO', 'CAMINADORA', 1, 
REM     1, 6, 50);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (27, 6, 'MECANOTERAPIA GIMNASIO', 'EJERCICIOS CIRCULACION PERIFERICA', 1, 
REM     1, 6, 34);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (28, 6, 'MECANOTERAPIA GIMNASIO', 'EJERCICIOS DE CIFOSIS/ESCOLIOSIS', 1, 
REM     1, 6, 35);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (33, 6, 'MECANOTERAPIA GIMNASIO', 'EJERCICIOS DE CODMAN/PENDULARES', 1, 
REM     1, 6, 39);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (25, 6, 'MECANOTERAPIA GIMNASIO', 'EJERCICIOS DE RESISTENCIA PROGRESIVA', 1, 
REM     1, 6, 62);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (26, 6, 'MECANOTERAPIA GIMNASIO', 'EJERCICIOS FUNCIONALES DE COLCHON', 1, 
REM     1, 6, 33);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (41, 6, 'MECANOTERAPIA GIMNASIO', 'EJERCICIOS ISOMETRICOS', 1, 
REM     1, 6, 47);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (38, 6, 'MECANOTERAPIA GIMNASIO', 'ENTRENAMIENTO PARA TRASLADO Y TRANSFERENCIA', 1, 
REM     1, 6, 44);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (81, 6, 'MECANOTERAPIA GIMNASIO', 'HIGIENE DE COLUMNA', 1, 
REM     1, 6, 70);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (40, 6, 'MECANOTERAPIA GIMNASIO', 'MOVILIDAD ACTIVA ASISTIDA', 1, 
REM     1, 6, 46);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (39, 6, 'MECANOTERAPIA GIMNASIO', 'MOVILIDAD PASIVA', 1, 
REM     1, 6, 45);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (31, 6, 'MECANOTERAPIA GIMNASIO', 'MOVILIZACION DE ARCOS ARTICULARES', 1, 
REM     1, 6, 37);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (43, 6, 'MECANOTERAPIA GIMNASIO', 'ORBITREX', 1, 
REM     1, 6, 49);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (29, 6, 'MECANOTERAPIA GIMNASIO', 'REEDUCACION DE LA MARCHA Y POSTURA', 1, 
REM     1, 6, 36);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (30, 6, 'MECANOTERAPIA GIMNASIO', 'REEDUCACION MUSCULAR', 1, 
REM     1, 6, 63);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (34, 6, 'MECANOTERAPIA GIMNASIO', 'REHABILITACION CARDIACA', 1, 
REM     1, 6, 40);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (32, 6, 'MECANOTERAPIA GIMNASIO', 'RESTAURADOR DE HOMBRO', 1, 
REM     1, 6, 38);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (37, 6, 'MECANOTERAPIA GIMNASIO', 'TECNICAS DE ESTIRAMIENTO', 1, 
REM     1, 6, 43);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (35, 6, 'MECANOTERAPIA GIMNASIO', 'TECNICAS DE FACILITACION NEURO MUSCULAR', 1, 
REM     1, 6, 41);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (36, 6, 'MECANOTERAPIA GIMNASIO', 'TECNICAS PROPIO-EXTEROCEPCION', 1, 
REM     1, 6, 42);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (54, 9, 'TERAPIA OCUPACIONAL', 'EJERCICIOS DE RESISTENCIA PROGRESIVA', 1, 
REM     2, 7, 62);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (57, 9, 'TERAPIA OCUPACIONAL', 'TECNICAS PROPIO-EXTEROCEPCION', 1, 
REM     2, 7, 42);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (56, 9, 'TERAPIA OCUPACIONAL', 'TECNICAS DE FACILITACION NEURO MUSCULAR', 1, 
REM     2, 7, 41);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (58, 9, 'TERAPIA OCUPACIONAL', 'TECNICAS DE ESTIRAMIENTO', 1, 
REM     2, 7, 43);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (59, 9, 'TERAPIA OCUPACIONAL', 'TECNICA DE RELAJACION', 1, 
REM     2, 7, 59);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (60, 9, 'TERAPIA OCUPACIONAL', 'TECNICA DE COORDINACION', 1, 
REM     2, 7, 58);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (46, 9, 'TERAPIA OCUPACIONAL', 'TANQUE DE REMOLINO DE MIEMBROS SUPERIORES', 1, 
REM     2, 7, 12);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (55, 9, 'TERAPIA OCUPACIONAL', 'REEDUCACION MUSCULAR', 1, 
REM     2, 7, 63);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (66, 9, 'TERAPIA OCUPACIONAL', 'REDUCCION DE SENSIBILIDAD', 1, 
REM     2, 7, 68);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (64, 9, 'TERAPIA OCUPACIONAL', 'PENDULARES. REDUCCION/ENTRENAMIENTO DE A.V.D', 1, 
REM     2, 7, 66);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (45, 9, 'TERAPIA OCUPACIONAL', 'PARAFINA', 1, 
REM     2, 7, 10);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (101, 9, 'TERAPIA OCUPACIONAL', 'ONDAS DE CHOQUE', 1, 
REM     2, 7, 4);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (63, 9, 'TERAPIA OCUPACIONAL', 'MOVILIZACION ARTICULAR', 1, 
REM     2, 7, 65);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (67, 9, 'TERAPIA OCUPACIONAL', 'ACTIVIDAD RECREACIONAL', 1, 
REM     2, 7, 69);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (65, 9, 'TERAPIA OCUPACIONAL', 'ACTIVIDADES BASICAS DE LA MANO', 1, 
REM     2, 7, 67);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (62, 9, 'TERAPIA OCUPACIONAL', 'BICICLETA PARA MIEMBROS SUPERIORES', 1, 
REM     2, 7, 64);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (47, 9, 'TERAPIA OCUPACIONAL', 'COMPRESA QUIMICA CALIENTE', 1, 
REM     2, 7, 16);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (48, 9, 'TERAPIA OCUPACIONAL', 'COMPRESA QUIMICA FRIA', 1, 
REM     2, 7, 17);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (51, 9, 'TERAPIA OCUPACIONAL', 'ULTRASONIDO', 1, 
REM     2, 7, 24);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (52, 9, 'TERAPIA OCUPACIONAL', 'ELECTRO ESTIMULACION', 1, 
REM     2, 7, 21);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (49, 9, 'TERAPIA OCUPACIONAL', 'IONIZACIONES', 1, 
REM     2, 7, 22);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (50, 9, 'TERAPIA OCUPACIONAL', 'LASERTERAPIA', 1, 
REM     2, 7, 23);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (53, 9, 'TERAPIA OCUPACIONAL', 'MAGNETOTERAPIA', 1, 
REM     2, 7, 26);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (61, 9, 'TERAPIA OCUPACIONAL', 'MASAJE', 1, 
REM     2, 7, 31);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (73, 10, 'TERAPIA DE LENGUAJE', 'TERAPIA LECTO ESCRITURA', 1, 
REM     3, 8, 56);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (72, 10, 'TERAPIA DE LENGUAJE', 'TERAPIA DEL LENGUAJE', 1, 
REM     3, 8, 55);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (71, 10, 'TERAPIA DE LENGUAJE', 'TERAPIA DEL HABLA', 1, 
REM     3, 8, 54);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (69, 10, 'TERAPIA DE LENGUAJE', 'TERAPIA DE LA VOZ', 1, 
REM     3, 8, 52);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (70, 10, 'TERAPIA DE LENGUAJE', 'TERAPIA DE AUDICION', 1, 
REM     3, 8, 53);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (68, 10, 'TERAPIA DE LENGUAJE', 'TERAPIA ARTICULATORIA', 1, 
REM     3, 8, 51);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (79, 10, 'TERAPIA DE LENGUAJE', 'TECNICA DE RESPIRACION', 1, 
REM     3, 8, 61);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (77, 10, 'TERAPIA DE LENGUAJE', 'TECNICA DE RELAJACION', 1, 
REM     3, 8, 59);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (76, 10, 'TERAPIA DE LENGUAJE', 'TECNICA DE COORDINACION', 1, 
REM     3, 8, 58);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (78, 10, 'TERAPIA DE LENGUAJE', 'REEDUCACION DE ESCRITURA', 1, 
REM     3, 8, 60);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (75, 10, 'TERAPIA DE LENGUAJE', 'MEMORIA', 1, 
REM     3, 8, 57);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (74, 10, 'TERAPIA DE LENGUAJE', 'MASAJE', 1, 
REM     3, 8, 31);
REM Insert into ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
REM    (TTE_ID, TER_ID, TER_DESCRIPCION, TRA_DESCRIPCION, REVISADO, 
REM     PROID0NIVEL, PROID1NIVEL, PROID2NIVEL)
REM  Values
REM    (102, 12, 'ONDAS DE CHOQUE', 'LASERTERAPIA', 1, 
REM     4, 9, 23);
REM COMMIT;
REM 