WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
  SELECT '@C:\logs\sql_migra_fisiatria7.sql ' || MEF_PLANIF_TRATAM.PTR_ID || ';'
            sqlm
    FROM ADMINISTRATIVO.MEF_PLANIF_TRATAM
ORDER BY 1 DESC;