/* Formatted on 17/06/2016 12:11:03 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING OFF
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF

SELECT    '@C:\logs\fisiatria\FISIATRIA\migra_registros\sql_migra_fisiatriaC_RECONSTRUCCION.sql '
       || PTR_ID
       || ';'
  FROM MEF_PLANIF_TRATAM;