WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
SELECT '@C:\LOGS\sql_migra_fisiatriaC_RECONSTRUCCION.sql ' || PTR_ID || ';'
  FROM MEF_PLANIF_TRATAM;