/* Formatted on 17/06/2016 11:37:41 (QP5 v5.252.13127.32867) */
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->DROP TABLE ADMINISTRATIVO.AA_PERFISI CASCADE CONSTRAINTS;
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->CREATE TABLE ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->(
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->  PME_ID  INTEGER
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (286);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (287);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (288);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (289);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (290);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (291);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (292);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (293);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (294);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (295);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (296);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (297);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (298);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (299);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (300);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (301);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (302);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (303);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (304);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (305);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (306);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (307);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (308);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (309);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (310);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->Insert into ADMINISTRATIVO.AA_PERFISI
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (PME_ID)
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS-----> Values
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->   (311);
REM ESTE PERSONAL DEBE ESTAR CARGADO Y DEBE TENER UNA SALA DE PROCEDIMIENTOS----->COMMIT;



  SELECT *
    FROM MED_PARSCO_PERMED
   WHERE     PME_ID IN (SELECT PME_ID
                          FROM (SELECT MED_PERSONAL_MEDICO.PME_ID,
                                       (SELECT COUNT (*)
                                          FROM ADMINISTRATIVO.MED_PARSCO_PERMED
                                         WHERE     PME_ID =
                                                      MED_PERSONAL_MEDICO.PME_ID
                                               AND ADMINISTRATIVO.MED_PARSCO_PERMED.PPM_ESTADO =
                                                      'A')
                                          TOTAL_SUBIDOS,
                                       MED_PERSONAL_MEDICO.EMP_ID
                                  FROM ADMINISTRATIVO.MED_PERSONAL_MEDICO
                                 WHERE MED_PERSONAL_MEDICO.PME_ID IN (SELECT PME_ID
                                                                        FROM AA_PERFISI))
                         WHERE TOTAL_SUBIDOS IN (0) OR TOTAL_SUBIDOS > 1)
         AND PPM_ESTADO = 'A'
ORDER BY PME_ID;



PAUSE REVISAR QUE NO SE TENGA MÁS DE UNA SALA CONSULTORIO HABILITADO A TODOS LOS FISIATRAS


REM REVISAR LOS FISIATRAS QUE SE ALMACENABAN EN LA CABECERA TRATAMIENTO

  SELECT DISTINCT pme_id
    FROM ADMINISTRATIVO.MEF_CAB_TRATAM
ORDER BY 1;



REM

SELECT MED_PERSONAL_MEDICO.PME_ID,
       MED_PERSONAL_MEDICO.EMP_ID,
       CGG_PERSONA.PER_ID,
       CGG_PERSONA.PER_DNI,
       MED_PERSONAL_MEDICO.ESE_ID,
       CGG_PERSONA.PER_PRIMER_NOMBRE,
       CGG_PERSONA.PER_SEGUNDO_NOMBRE,
       CGG_PERSONA.PER_PRIMER_APELLIDO,
       CGG_PERSONA.PER_SEGUNDO_APELLIDO TIENE_SALA,
       (SELECT COUNT (*)
          FROM ADMINISTRATIVO.MED_PARSCO_PERMED
         WHERE     MED_PARSCO_PERMED.PPM_ESTADO = 'A'
               AND MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID)
          CUANTAS_SALAS,
       (SELECT CGG_DISTRIBUCION_FISICA.DFI_ID
          FROM ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
         WHERE     MED_PARSCO_PERMED.PPM_ESTADO = 'A'
               AND MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID)
          DFI_ASOCIADO,
       (SELECT MED_PROCEDIMIENTO.PRO_DESCRIPCION
          FROM ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
               INNER JOIN ADMINISTRATIVO.MED_PROCEDIMIENTO_SALCON
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PROCEDIMIENTO_SALCON.DFI_ID)
               INNER JOIN ADMINISTRATIVO.MED_PROCEDIMIENTO_ESPSER
                  ON (MED_PROCEDIMIENTO_ESPSER.PES_ID =
                         MED_PROCEDIMIENTO_SALCON.PES_ID)
               INNER JOIN ADMINISTRATIVO.MED_PROCEDIMIENTO
                  ON (MED_PROCEDIMIENTO.PRO_ID =
                         MED_PROCEDIMIENTO_ESPSER.PRO_ID)
         WHERE     MED_PARSCO_PERMED.PPM_ESTADO = 'A'
               AND MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID)
          NOMBRE_PROCED,
       (SELECT CGG_DISTRIBUCION_FISICA.DFI_DESCRIPCION
          FROM ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
         WHERE     MED_PARSCO_PERMED.PPM_ESTADO = 'A'
               AND MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID)
          NOMBRESALCON,
       (SELECT CGG_DISTRIBUCION_FISICA.DFI_SIGLAS
          FROM ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
         WHERE     MED_PARSCO_PERMED.PPM_ESTADO = 'A'
               AND MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID)
          SIGLAS_SALCON,
       (SELECT CGG_DISTRIBUCION_FISICA.DFI_TIPO
          FROM ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
         WHERE     MED_PARSCO_PERMED.PPM_ESTADO = 'A'
               AND MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID)
          TIPOSALCON
  FROM ADMINISTRATIVO.APP_EMPLEADO
       INNER JOIN ADMINISTRATIVO.MED_PERSONAL_MEDICO
          ON (APP_EMPLEADO.EMP_ID = MED_PERSONAL_MEDICO.EMP_ID)
       INNER JOIN ADMINISTRATIVO.CGG_PERSONA
          ON (CGG_PERSONA.PER_ID = APP_EMPLEADO.PER_ID)
 WHERE MED_PERSONAL_MEDICO.PME_ID IN (SELECT AA_PERFISI.PME_ID
                                        FROM ADMINISTRATIVO.AA_PERFISI);