/* Formatted on 14/06/2016 15:03:07 (QP5 v5.252.13127.32867) */
REM VALIDAR QUE FISIATRAS TIENEN ASOCIADO UN CONSULTORIO

  SELECT DISTINCT
         MEF_CAB_TRATAM.PME_ID,
         (SELECT MED_PARAMETRIZACION_SALCON.PSC_ID
            FROM ADMINISTRATIVO.MED_PARSCO_PERMED,
                 ADMINISTRATIVO.MED_PARAMETRIZACION_SALCON
           WHERE     MED_PARSCO_PERMED.PME_ID = MEF_CAB_TRATAM.PME_ID
                 AND MED_PARAMETRIZACION_SALCON.PSC_ID =
                        MED_PARSCO_PERMED.PSC_ID)
            PSC_ID
    FROM ADMINISTRATIVO.MEF_CAB_TRATAM
ORDER BY 1