REM SE DEBE DETERMINAR LOS FISIATRAS QUE NO TENGAN ASOCIO SU SALA O CONSULTORIOE

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
SELECT CGG_PERSONA.PER_PRIMER_APELLIDO,
       CGG_PERSONA.PER_PRIMER_NOMBRE,
       CGG_PERSONA.PER_SEGUNDO_APELLIDO,
       CGG_PERSONA.PER_SEGUNDO_NOMBRE,
       CGG_PERSONA.PER_DNI,
       MED_PERSONAL_MEDICO.PME_ID
  FROM ADMINISTRATIVO.CGG_PERSONA,
       ADMINISTRATIVO.MED_PERSONAL_MEDICO,
       ADMINISTRATIVO.APP_EMPLEADO
 WHERE     CGG_PERSONA.PER_PRIMER_APELLIDO LIKE '%BARR%'
       AND APP_EMPLEADO.EMP_ID = MED_PERSONAL_MEDICO.EMP_ID
       AND CGG_PERSONA.PER_ID = APP_EMPLEADO.PER_ID;