/* Formatted on 16/06/2016 15:10:04 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
SET TERMOUT OFF

SELECT *
  FROM MED_SOLICITUD_PROCEDIMIENTO
 WHERE SPR_ID = '&&V_SPR_ID';

DELETE FROM ADMINISTRATIVO.MED_SOLICITUD_DETALLE_PROC
      WHERE SPR_ID = '&&V_SPR_ID';


DELETE FROM MED_TURNO_ATENCION
      WHERE TPR_ID IN (SELECT MED_TURNO_PROCEDIMIENTO.TPR_ID
                         FROM ADMINISTRATIVO.MED_TURNO_PROCEDIMIENTO
                        WHERE MED_TURNO_PROCEDIMIENTO.SPR_ID = '&&V_SPR_ID');


DELETE FROM MED_TURNO_ATENCION
      WHERE TPR_ID IN (SELECT MED_TURNO_PROCEDIMIENTO.TPR_ID
                         FROM ADMINISTRATIVO.MED_TURNO_PROCEDIMIENTO
                        WHERE MED_TURNO_PROCEDIMIENTO.SPR_ID = '&&V_SPR_ID');

DELETE FROM MED_TURNO_DETALLE
      WHERE TPR_ID IN (SELECT MED_TURNO_PROCEDIMIENTO.TPR_ID
                         FROM ADMINISTRATIVO.MED_TURNO_PROCEDIMIENTO
                        WHERE MED_TURNO_PROCEDIMIENTO.SPR_ID = '&&V_SPR_ID');

DELETE FROM MED_TURNO_PROCEDIMIENTO
      WHERE SPR_ID = '&&V_SPR_ID';


DELETE FROM MED_SOLICITUD_PROCEDIMIENTO
      WHERE SPR_ID = '&&V_SPR_ID';