/* Formatted on 13/06/2016 13:13:30 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF
COLUMN TTE_ID HEADING "TTE_ID" FORMAT A10  TRUNC  NEW_VALUE V_TTE_ID
COLUMN TER_ID HEADING "TER_ID" FORMAT A10  TRUNC  NEW_VALUE V_TER_ID
COLUMN TER_DESCRIPCION HEADING "TER_DESCRIPCION" FORMAT A30  TRUNC  NEW_VALUE V_TER_DESCRIPCION
COLUMN TRA_DESCRIPCION HEADING "TRA_DESCRIPCION" FORMAT A30  TRUNC  NEW_VALUE V_TRA_DESCRIPCION


DECLARE
   CURSOR CURS
   IS
      SELECT 'DROP TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED' TEXT FROM DUAL;

   C_ROW         CURS%ROWTYPE;
   CURSOR_NAME   INTEGER;
BEGIN
   FOR C_ROW IN CURS
   LOOP
      CURSOR_NAME := DBMS_SQL.OPEN_CURSOR;
      DBMS_SQL.PARSE (CURSOR_NAME, C_ROW.TEXT, DBMS_SQL.NATIVE);
      DBMS_SQL.CLOSE_CURSOR (CURSOR_NAME);
   END LOOP;
END;
/

CREATE TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED

AS
   SELECT INLINEVIEW_1.TTE_ID,
          INLINEVIEW_1.TER_ID,
          INLINEVIEW_1.TER_DESCRIPCION,
          INLINEVIEW_1.TRA_DESCRIPCION
     FROM (  SELECT MED_TRATAM_TERAPIA.TTE_ID,
                    MED_TERAPIA.TER_ID,
                    MED_TERAPIA.TER_DESCRIPCION,
                    MED_TRATAMIENTO.TRA_DESCRIPCION
               FROM ADMINISTRATIVO.MED_TRATAMIENTO,
                    ADMINISTRATIVO.MED_TRATAM_TERAPIA,
                    ADMINISTRATIVO.MED_TERAPIA
              WHERE     MED_TRATAMIENTO.TRA_ID = MED_TRATAM_TERAPIA.TRA_ID
                    AND MED_TRATAM_TERAPIA.TER_ID = MED_TERAPIA.TER_ID
           ORDER BY MED_TERAPIA.TER_DESCRIPCION,
                    MED_TRATAMIENTO.TRA_DESCRIPCION) INLINEVIEW_1;
	
					
ALTER TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
ADD (REVISADO INTEGER DEFAULT 0);
ALTER TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
ADD (PROID0NIVEL INTEGER DEFAULT 0);
ALTER TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
ADD (PROID1NIVEL INTEGER DEFAULT 0);
ALTER TABLE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
ADD (PROID2NIVEL INTEGER DEFAULT 0);