/* Formatted on 17/06/2016 10:33:34 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF


REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 
REM ACA SE IGUALAN EN LA TABLA ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED LOS CAMPOS NIVEL 0 Y NIVEL1 



UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.PROID0NIVEL = 1,
       AA_TABLA_EQUIV_PROCED.PROID1NIVEL = 6,
       AA_TABLA_EQUIV_PROCED.REVISADO = 1
 WHERE AA_TABLA_EQUIV_PROCED.TER_ID = 5;

UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.PROID0NIVEL = 1,
       AA_TABLA_EQUIV_PROCED.PROID1NIVEL = 5,
       AA_TABLA_EQUIV_PROCED.REVISADO = 1
 WHERE AA_TABLA_EQUIV_PROCED.TER_ID = 4;


UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.PROID0NIVEL = 1,
       AA_TABLA_EQUIV_PROCED.PROID1NIVEL = 6,
       AA_TABLA_EQUIV_PROCED.REVISADO = 1
 WHERE AA_TABLA_EQUIV_PROCED.TER_ID = 6;


UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.PROID0NIVEL = 4,
       AA_TABLA_EQUIV_PROCED.PROID1NIVEL = 9,
       AA_TABLA_EQUIV_PROCED.REVISADO = 1
 WHERE AA_TABLA_EQUIV_PROCED.TER_ID = 12;



UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.PROID0NIVEL = 3,
       AA_TABLA_EQUIV_PROCED.PROID1NIVEL = 8,
       AA_TABLA_EQUIV_PROCED.REVISADO = 1
 WHERE AA_TABLA_EQUIV_PROCED.TER_ID = 10;



UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.PROID0NIVEL = 2,
       AA_TABLA_EQUIV_PROCED.PROID1NIVEL = 7,
       AA_TABLA_EQUIV_PROCED.REVISADO = 1
 WHERE AA_TABLA_EQUIV_PROCED.TER_ID = 9;



COMMIT;

COLUMN ENCERAR HEADING "ENCERAR" FORMAT A20  TRUNC  NEW_VALUE V_ENCERAR

SELECT '&&PNER_REVISADO_0_S_O_N.' ENCERAR FROM DUAL;


DECLARE
BEGIN
   IF UPPER ('&&V_ENCERAR') IN ('S', 'SI', 'SÍ')
   THEN
      UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
         SET ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED.REVISADO = 0;

      COMMIT;
   END IF;

   COMMIT;
END;

COLUMN TTE_ID FORMAT A20 TRUNC NEW_VALUE V_TTE_ID
COLUMN TER_ID FORMAT A20 TRUNC NEW_VALUE V_TER_ID
COLUMN TER_DESCRIPCION FORMAT A20 TRUNC NEW_VALUE V_TER_DESCRIPCION
COLUMN TRA_DESCRIPCION FORMAT A40 TRUNC NEW_VALUE V_TRA_DESCRIPCION
COLUMN REVISADO FORMAT A20 TRUNC NEW_VALUE V_REVISADO
COLUMN PROID2NIVEL FORMAT A20 TRUNC NEW_VALUE V_PROID2NIVEL



REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2
REM ACA SE OMOLOGAN LOS PROCEDIMIENTOS DE ESPECIALIDAD SERVICIO Y SE ACTUALIZA Y ASOCIA EN LOS NIVELES 0,1,2


  SELECT AA_TABLA_EQUIV_PROCED.TTE_ID,
         AA_TABLA_EQUIV_PROCED.TER_ID,
         AA_TABLA_EQUIV_PROCED.TER_DESCRIPCION,
         AA_TABLA_EQUIV_PROCED.TRA_DESCRIPCION,
         AA_TABLA_EQUIV_PROCED.REVISADO,
         AA_TABLA_EQUIV_PROCED.PROID2NIVEL
    FROM ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   WHERE ROWNUM = 1 AND REVISADO = 0
ORDER BY PROID2NIVEL;


PAUSE INGRESE

COLUMN n0 HEADING "n0" FORMAT A10  TRUNC  NEW_VALUE V_n0
COLUMN n1 HEADING "n1" FORMAT A10  TRUNC  NEW_VALUE V_n1
COLUMN n2 HEADING "n2" FORMAT A10  TRUNC  NEW_VALUE V_n2
COLUMN PRO_DESCRIPCION HEADING "PRO_DESCRIPCION" FORMAT A20  TRUNC  NEW_VALUE V_PRO_DESCRIPCION
COLUMN PRO_DESCRIPCION_1 HEADING "PRO_DESCRIPCION_1" FORMAT A20  TRUNC  NEW_VALUE V_PRO_DESCRIPCION_1
COLUMN PRO_DESCRIPCION_2 HEADING "PRO_DESCRIPCION_2" FORMAT A20  TRUNC  NEW_VALUE V_PRO_DESCRIPCION_2



  SELECT "n0".PRO_DESCRIPCION,
         "n1".PRO_DESCRIPCION,
         "n2".PRO_DESCRIPCION,
         "n1".PRO_ID n1
    FROM ADMINISTRATIVO.V_PROCED_TRES_NIV,
         ADMINISTRATIVO.MED_PROCEDIMIENTO "n1",
         ADMINISTRATIVO.MED_PROCEDIMIENTO "n0",
         ADMINISTRATIVO.MED_PROCEDIMIENTO "n2"
   WHERE     V_PROCED_TRES_NIV.NIVEL1_PRO_ID = "n1".PRO_ID
         AND "n0".PRO_ID = V_PROCED_TRES_NIV.NIVEL0_PRO_ID
         AND "n2".PRO_ID = V_PROCED_TRES_NIV.NIVEL2_PRO_ID
         AND "n2".PRO_DESCRIPCION = '&&V_TRA_DESCRIPCION.'
ORDER BY "n1".PRO_ID;

PAUSE DE LAS POSIBILIDADES SELECCIONE EL QUE CORRESPONDA, SE DEBE REVISAR MINUSCIOSAMENTE

COLUMN n0 HEADING "n0" FORMAT A10  TRUNC  NEW_VALUE V_n0
COLUMN n1 HEADING "n1" FORMAT A10  TRUNC  NEW_VALUE V_n1
COLUMN n2 HEADING "n2" FORMAT A10  TRUNC  NEW_VALUE V_n2

SELECT "n0".PRO_DESCRIPCION,
       "n1".PRO_DESCRIPCION,
       "n2".PRO_DESCRIPCION,
       "n0".PRO_ID n0,
       "n1".PRO_ID n1,
       "n2".PRO_ID n2
  FROM ADMINISTRATIVO.V_PROCED_TRES_NIV,
       ADMINISTRATIVO.MED_PROCEDIMIENTO "n1",
       ADMINISTRATIVO.MED_PROCEDIMIENTO "n0",
       ADMINISTRATIVO.MED_PROCEDIMIENTO "n2"
 WHERE     V_PROCED_TRES_NIV.NIVEL1_PRO_ID = "n1".PRO_ID
       AND "n0".PRO_ID = V_PROCED_TRES_NIV.NIVEL0_PRO_ID
       AND "n2".PRO_ID = V_PROCED_TRES_NIV.NIVEL2_PRO_ID
       AND "n2".PRO_DESCRIPCION = '&&V_TRA_DESCRIPCION.'
       AND "n1".PRO_ID = '&&seleccione_PRO_ID_DEL_NIVEL1.';


PAUSE selecciono  '&&V_n0.'   '&&V_n1.'  '&&V_n2.'

UPDATE ADMINISTRATIVO.AA_TABLA_EQUIV_PROCED
   SET AA_TABLA_EQUIV_PROCED.PROID0NIVEL = '&&V_n0.',
       AA_TABLA_EQUIV_PROCED.PROID1NIVEL = '&&V_n1.',
       revisado = 1
 WHERE     AA_TABLA_EQUIV_PROCED.PROID2NIVEL = '&&V_n2.'
       AND TER_ID = '&&V_TER_ID.'
       AND TTE_ID = '&&V_TTE_ID.';



SELECT *
  FROM AA_TABLA_EQUIV_PROCED
 WHERE     AA_TABLA_EQUIV_PROCED.PROID2NIVEL = '&&V_n2.'
       AND AA_TABLA_EQUIV_PROCED.PROID1NIVEL = '&&V_n1.';

BEGIN
   IF TRIM (UPPER ('&&GRABAR')) = 'S'
   THEN
      COMMIT;
      DBMS_OUTPUT.PUT_LINE ('GRABO');
   ELSE
      ROLLBACK;
      DBMS_OUTPUT.PUT_LINE ('NO GRABO');
   END IF;
END;
/