/* Formatted on 15/06/2016 11:55:38 (QP5 v5.252.13127.32867) */
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;
SET SERVEROUTPUT ON
SET LINESIZE 1000
SET PAGESIZE 1000
SET ECHO OFF
SET HEADING ON
SET FEEDBACK OFF
SET TIMING OFF
SET VERIFY OFF


REM PERSONAL DE FISIATRIA PME_ID---->CREATE TABLE ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->(
REM PERSONAL DE FISIATRIA PME_ID---->  PME_ID  INTEGER
REM PERSONAL DE FISIATRIA PME_ID---->)
REM PERSONAL DE FISIATRIA PME_ID---->
REM PERSONAL DE FISIATRIA PME_ID---->
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (286);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (287);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (288);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (289);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (290);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (291);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (292);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (293);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (294);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (295);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (296);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (297);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (298);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (299);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (300);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (301);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (302);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (303);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (304);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (305);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (306);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (307);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (308);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (309);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (310);
REM PERSONAL DE FISIATRIA PME_ID---->Insert into ADMINISTRATIVO.AA_PERFISI
REM PERSONAL DE FISIATRIA PME_ID---->   (PME_ID)
REM PERSONAL DE FISIATRIA PME_ID----> Values
REM PERSONAL DE FISIATRIA PME_ID---->   (311);
REM PERSONAL DE FISIATRIA PME_ID---->COMMIT;
REM 



REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->  SELECT CGG_SERVICIO.SER_DESCRIPCION,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         APN_DEPENDENCIA.DEP_DESCRIPCION,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_ID,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.ESE_ID,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_DESCRIPCION,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_SIGLAS,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_TIPO,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_TIEMPO_PRIMERA_VEZ,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_PRIMERA_VEZ,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_SUBSECUENTES,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_NIVEL,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_ESTADO,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_FECHA_CREACION,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_TIPO_VALOR,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_TIEMPO_SUBSECUENTE,
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         CGG_DISTRIBUCION_FISICA.DFI_ULTIMO_NIVEL
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->    FROM ADMINISTRATIVO.CGG_ESPECIALIDAD_SERVICIO
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         INNER JOIN ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->            ON (CGG_ESPECIALIDAD_SERVICIO.ESE_ID =
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->                   CGG_DISTRIBUCION_FISICA.ESE_ID)
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         INNER JOIN ADMINISTRATIVO.CGG_SERVICIO
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->            ON (CGG_SERVICIO.SER_ID = CGG_ESPECIALIDAD_SERVICIO.SER_ID)
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->         INNER JOIN ADMINISTRATIVO.APN_DEPENDENCIA
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->            ON (APN_DEPENDENCIA.DEP_ID = CGG_ESPECIALIDAD_SERVICIO.DEP_ID)
REM CRUCE DE ESPECIALIDAD SERVICIO CON DISTRIB FISICA--->ORDER BY CGG_SERVICIO.SER_DESCRIPCION



REM
REM SELECT MEF_CAB_TRATAM.PME_ID FROM ADMINISTRATIVO.MEF_CAB_TRATAM
REM UNION
REM SELECT MED_PARSCO_PERMED.PME_ID FROM ADMINISTRATIVO.MED_PARSCO_PERMED;
REM
REM
REM
REM
REM SELECT MEF_CAB_TRATAM.PME_ID FROM ADMINISTRATIVO.MEF_CAB_TRATAM
REM INTERSECT
REM SELECT MED_PARSCO_PERMED.PME_ID FROM ADMINISTRATIVO.MED_PARSCO_PERMED;



  SELECT 'TERAPISTAS EXISTENTES EN TABLAS ANTERIORES' TE,
         CGG_PERSONA.PER_DNI,
         CGG_PERSONA.PER_ID,
         CGG_PERSONA.PER_PRIMER_APELLIDO,
         CGG_PERSONA.PER_SEGUNDO_APELLIDO,
         CGG_PERSONA.PER_PRIMER_NOMBRE,
         CGG_PERSONA.PER_SEGUNDO_NOMBRE,
         MED_PERSONAL_MEDICO.PME_ID
    FROM ADMINISTRATIVO.APP_EMPLEADO
         INNER JOIN ADMINISTRATIVO.MED_PERSONAL_MEDICO
            ON (APP_EMPLEADO.EMP_ID = MED_PERSONAL_MEDICO.EMP_ID)
         INNER JOIN ADMINISTRATIVO.CGG_PERSONA
            ON (APP_EMPLEADO.PER_ID = CGG_PERSONA.PER_ID)
   WHERE MED_PERSONAL_MEDICO.PME_ID IN (SELECT MEF_CAB_TRATAM.PME_ID
                                          FROM ADMINISTRATIVO.MEF_CAB_TRATAM)
ORDER BY CGG_PERSONA.PER_PRIMER_APELLIDO, CGG_PERSONA.PER_SEGUNDO_APELLIDO;



  SELECT CGG_DISTRIBUCION_FISICA.DFI_ID,
         CGG_SERVICIO.SER_DESCRIPCION,
         APN_DEPENDENCIA.DEP_DESCRIPCION,
         CGG_DISTRIBUCION_FISICA.ESE_ID,
         CGG_DISTRIBUCION_FISICA.DFI_DESCRIPCION,
         CGG_DISTRIBUCION_FISICA.DFI_SIGLAS,
         CGG_DISTRIBUCION_FISICA.DFI_TIPO,
         CGG_DISTRIBUCION_FISICA.DFI_TIEMPO_PRIMERA_VEZ,
         CGG_DISTRIBUCION_FISICA.DFI_PRIMERA_VEZ,
         CGG_DISTRIBUCION_FISICA.DFI_SUBSECUENTES,
         CGG_DISTRIBUCION_FISICA.DFI_NIVEL,
         CGG_DISTRIBUCION_FISICA.DFI_ESTADO,
         CGG_DISTRIBUCION_FISICA.DFI_FECHA_CREACION,
         CGG_DISTRIBUCION_FISICA.DFI_TIPO_VALOR,
         CGG_DISTRIBUCION_FISICA.DFI_TIEMPO_SUBSECUENTE,
         CGG_DISTRIBUCION_FISICA.DFI_ULTIMO_NIVEL
    FROM ADMINISTRATIVO.CGG_ESPECIALIDAD_SERVICIO
         INNER JOIN ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
            ON (CGG_ESPECIALIDAD_SERVICIO.ESE_ID =
                   CGG_DISTRIBUCION_FISICA.ESE_ID)
         INNER JOIN ADMINISTRATIVO.CGG_SERVICIO
            ON (CGG_SERVICIO.SER_ID = CGG_ESPECIALIDAD_SERVICIO.SER_ID)
         INNER JOIN ADMINISTRATIVO.APN_DEPENDENCIA
            ON (APN_DEPENDENCIA.DEP_ID = CGG_ESPECIALIDAD_SERVICIO.DEP_ID)
   WHERE APN_DEPENDENCIA.DEP_DESCRIPCION = 'MEDICINA FISICA Y REHABILITACION'
ORDER BY CGG_SERVICIO.SER_DESCRIPCION,
         CGG_DISTRIBUCION_FISICA.DFI_DESCRIPCION;

COLUMN PPM_ID FORMAT A20 TRUNC NEW_VALUE V_PPM_ID
COLUMN PME_ID FORMAT A20 TRUNC NEW_VALUE V_PME_ID
COLUMN PPM_ESTADO FORMAT A20 TRUNC NEW_VALUE V_PPM_ESTADO
COLUMN PPM_FECHA_CREACION FORMAT A20 TRUNC NEW_VALUE V_PPM_FECHA_CREACION
COLUMN DFI_ID FORMAT A20 TRUNC NEW_VALUE V_DFI_ID
COLUMN PPM_FECHA_DESDE FORMAT A20 TRUNC NEW_VALUE V_PPM_FECHA_DESDE
COLUMN PME_ID_REEMPLAZO FORMAT A20 TRUNC NEW_VALUE V_PME_ID_REEMPLAZO
COLUMN PPM_FECHA_HASTA FORMAT A20 TRUNC NEW_VALUE V_PPM_FECHA_HASTA
COLUMN PPM_OBSERVACION FORMAT A20 TRUNC NEW_VALUE V_PPM_OBSERVACION


REM PAUSE SAQUE A EXCEL

SELECT '&&SEL_PME_ID' PME_ID FROM DUAL;

SELECT '&&SEL_DFI_ID' PME_ID FROM DUAL;

SELECT *
  FROM ADMINISTRATIVO.MED_PARSCO_PERMED
 WHERE MED_PARSCO_PERMED.PME_ID = '&&SEL_PME_ID';


PAUSE REVISE ANTES

INSERT INTO ADMINISTRATIVO.MED_PARSCO_PERMED (PPM_ID,
                                              PME_ID,
                                              PPM_ESTADO,
                                              PPM_FECHA_CREACION,
                                              DFI_ID)
     VALUES (-1,
             '&&SEL_PME_ID',
             'A',
             SYSDATE,
             '&&SEL_DFI_ID');



SELECT *
  FROM ADMINISTRATIVO.MED_PARSCO_PERMED
 WHERE MED_PARSCO_PERMED.PME_ID = '&&SEL_PME_ID';

PAUSE REVISE DESPUES


SELECT 'TERAPISTAS EXISTENTES EN TABLAS ANTERIORES' TE,
       CGG_PERSONA.PER_DNI,
       CGG_PERSONA.PER_ID,
       CGG_PERSONA.PER_PRIMER_APELLIDO,
       CGG_PERSONA.PER_SEGUNDO_APELLIDO,
       CGG_PERSONA.PER_PRIMER_NOMBRE,
       CGG_PERSONA.PER_SEGUNDO_NOMBRE,
       MED_PERSONAL_MEDICO.PME_ID,
       (SELECT CGG_SERVICIO.SER_DESCRIPCION
          FROM ADMINISTRATIVO.CGG_ESPECIALIDAD_SERVICIO
               INNER JOIN ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
                  ON (CGG_ESPECIALIDAD_SERVICIO.ESE_ID =
                         CGG_DISTRIBUCION_FISICA.ESE_ID)
               INNER JOIN ADMINISTRATIVO.APN_DEPENDENCIA
                  ON (APN_DEPENDENCIA.DEP_ID =
                         CGG_ESPECIALIDAD_SERVICIO.DEP_ID)
               INNER JOIN ADMINISTRATIVO.CGG_SERVICIO
                  ON (CGG_SERVICIO.SER_ID = CGG_ESPECIALIDAD_SERVICIO.SER_ID)
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
         WHERE     MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID
               AND CGG_DISTRIBUCION_FISICA.DFI_ID = '&&SEL_DFI_ID'
               AND ROWNUM = 1)
          SERVICIO,
       (SELECT APN_DEPENDENCIA.DEP_DESCRIPCION
          FROM ADMINISTRATIVO.CGG_ESPECIALIDAD_SERVICIO
               INNER JOIN ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
                  ON (CGG_ESPECIALIDAD_SERVICIO.ESE_ID =
                         CGG_DISTRIBUCION_FISICA.ESE_ID)
               INNER JOIN ADMINISTRATIVO.APN_DEPENDENCIA
                  ON (APN_DEPENDENCIA.DEP_ID =
                         CGG_ESPECIALIDAD_SERVICIO.DEP_ID)
               INNER JOIN ADMINISTRATIVO.CGG_SERVICIO
                  ON (CGG_SERVICIO.SER_ID = CGG_ESPECIALIDAD_SERVICIO.SER_ID)
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
         WHERE     MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID
               AND CGG_DISTRIBUCION_FISICA.DFI_ID = '&&SEL_DFI_ID'
               AND ROWNUM = 1)
          DEPENDENCIA,
       (SELECT CGG_DISTRIBUCION_FISICA.DFI_DESCRIPCION
          FROM ADMINISTRATIVO.CGG_ESPECIALIDAD_SERVICIO
               INNER JOIN ADMINISTRATIVO.CGG_DISTRIBUCION_FISICA
                  ON (CGG_ESPECIALIDAD_SERVICIO.ESE_ID =
                         CGG_DISTRIBUCION_FISICA.ESE_ID)
               INNER JOIN ADMINISTRATIVO.APN_DEPENDENCIA
                  ON (APN_DEPENDENCIA.DEP_ID =
                         CGG_ESPECIALIDAD_SERVICIO.DEP_ID)
               INNER JOIN ADMINISTRATIVO.CGG_SERVICIO
                  ON (CGG_SERVICIO.SER_ID = CGG_ESPECIALIDAD_SERVICIO.SER_ID)
               INNER JOIN ADMINISTRATIVO.MED_PARSCO_PERMED
                  ON (CGG_DISTRIBUCION_FISICA.DFI_ID =
                         MED_PARSCO_PERMED.DFI_ID)
         WHERE     MED_PARSCO_PERMED.PME_ID = MED_PERSONAL_MEDICO.PME_ID
               AND CGG_DISTRIBUCION_FISICA.DFI_ID = '&&SEL_DFI_ID'
               AND ROWNUM = 1)
          DISTRIBFIS
  FROM ADMINISTRATIVO.APP_EMPLEADO
       INNER JOIN ADMINISTRATIVO.MED_PERSONAL_MEDICO
          ON (APP_EMPLEADO.EMP_ID = MED_PERSONAL_MEDICO.EMP_ID)
       INNER JOIN ADMINISTRATIVO.CGG_PERSONA
          ON (APP_EMPLEADO.PER_ID = CGG_PERSONA.PER_ID)
 WHERE MED_PERSONAL_MEDICO.PME_ID = '&&SEL_PME_ID';

COMMIT;